// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Respository.Models
{
    public partial class Account
    {
        [Key]
        [Column("uID")]
        public int UId { get; set; }
        [Column("user")]
        [StringLength(50)]
        public string User { get; set; }
        [Column("pass")]
        [StringLength(50)]
        public string Pass { get; set; }
        [Column("isSell")]
        public bool? IsSell { get; set; }
        [Column("isAdmin")]
        public bool? IsAdmin { get; set; }
        [Column("isCustomer")]
        public bool? IsCustomer { get; set; }
    }
}