// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Respository.Models
{
    [Keyless]
    public partial class Cart
    {
        [Column("AccountID")]
        public int? AccountId { get; set; }
        [Column("ProductID")]
        public int? ProductId { get; set; }
        public int? Amount { get; set; }
    }
}