// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Respository.Models
{
    public partial class Cart
    {
        [Key]
        [Column("ProductID")]
        public int ProductId { get; set; }
        public int? Amount { get; set; }
        [Column(TypeName = "money")]
        public decimal? Price { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
    }
}