// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Respository.Models
{
    public partial class Category
    {
        [Key]
        [Column("cid")]
        public int Cid { get; set; }
        [Required]
        [Column("cname")]
        [StringLength(50)]
        public string Cname { get; set; }
    }
}